const app=document.querySelector('#app'),homeButton=document.querySelector('#home-button');
const allKeys=[{id:'alice-public',label:'公開鍵',owner:'アリスの公開鍵',note:'だれでも使える'},{id:'alice-private',label:'秘密鍵',owner:'アリスの秘密鍵',note:'アリスだけが持つ'},{id:'bob-public',label:'公開鍵',owner:'ボブの公開鍵',note:'だれでも使える'},{id:'bob-private',label:'秘密鍵',owner:'ボブの秘密鍵',note:'ボブだけが持つ'}];
const state={mission:'home',step:0,direction:'alice-bob',encryptKey:null,decryptKey:null,signedHash:'',originalMessage:''};
function setScreen(html){app.innerHTML=html;app.focus({preventScroll:true});window.scrollTo({top:0,behavior:'smooth'})}
function progress(current,total){return `<div class="progress" aria-label="${total}段階中${current}段階">${Array.from({length:total},(_,i)=>`<span class="${i<current?'done':''}"></span>`).join('')}</div>`}
function head(kicker,title,lead,current,total){return `<div class="screen-head"><div><p class="kicker">${kicker}</p><h1>${title}</h1>${lead?`<p class="lead">${lead}</p>`:''}</div>${total?progress(current,total):''}</div>`}
function person(name,role){const data=name==='アリス'?{face:'👩‍💻',cls:'alice'}:{face:'👨‍💻',cls:'bob'};return `<div class="person ${data.cls}"><div class="avatar">${data.face}</div><strong>${name}</strong><small>${role}</small></div>`}
function keyCards(keys,selected){return `<div class="key-grid ${keys.length===3?'three':''}">${keys.map(k=>`<button class="key-card ${selected===k.id?'selected':''}" data-key="${k.id}"><span class="icon">🔑</span><b>${k.label}</b><strong>${k.owner}</strong><small>${k.note}</small></button>`).join('')}</div>`}
function button(label,id,kind='primary',disabled=false){return `<button id="${id}" class="button ${kind}" ${disabled?'disabled':''}>${label}</button>`}
function showHome(){state.mission='home';state.step=0;setScreen(`<section class="screen">${head('ミッションを選ぼう','暗号通信の仕組みを体験しよう','二人で相談し，「なぜ？」を言葉にしながら進めよう．')}<div class="hero-visual"><img src="classroom-crypto.png" alt="アリスが暗号化した手紙をボブに送り，イブの盗み見を防いでいるイラスト"><div class="hero-caption"><span>👩‍💻 送り手：アリス</span><span>👨‍💻 受け手：ボブ</span><span>🕵️ 盗み見する人：イブ</span></div></div><div class="mission-grid"><button class="mission-card" data-mission="shared"><span class="number">第1ミッション</span><span class="mission-icon">🤝🔑</span><strong>共通鍵暗号</strong><p>二人で同じ鍵を使う仕組み</p><em>はじめる →</em></button><button class="mission-card main" data-mission="public"><span class="number">第2ミッション｜中心課題</span><span class="mission-icon">📨🛡️</span><strong>公開鍵暗号</strong><p>イブに読まれず，相手だけが読める通信をつくる</p><em>はじめる →</em></button><button class="mission-card" data-mission="signature"><span class="number">第3ミッション</span><span class="mission-icon">✍️🔍</span><strong>デジタル署名</strong><p>送り手と，書き換えられていないことを確かめる</p><em>はじめる →</em></button></div><p class="mini-rule">どの鍵も同じ形の🔑です．<b>公開鍵・秘密鍵・共通鍵</b>という名前と，だれが持つかで見分けよう．</p></section>`);document.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>startMission(b.dataset.mission))}
function startMission(mission){state.mission=mission;state.step=1;state.encryptKey=null;state.decryptKey=null;if(mission==='public')renderPublic();if(mission==='shared')renderShared();if(mission==='signature')renderSignature()}
homeButton.onclick=showHome;
function bindKeys(field,render){document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>{state[field]=b.dataset.key;render()})}

function renderPublic(){
  const forward=state.direction==='alice-bob',sender=forward?'アリス':'ボブ',receiver=forward?'ボブ':'アリス';
  if(state.step===1){setScreen(`<section class="screen">${head('第2ミッション｜公開鍵暗号','通信の向きを選ぼう','まず，だれが送って，だれが受け取るかを決めます．',1,5)}<div class="panel"><h2 class="question">どちら向きに通信する？</h2><div class="route">${person('アリス',forward?'送り手':'受け手')}<div class="message"><b>${forward?'アリス → ボブ':'ボブ → アリス'}</b><span>📨 秘密のメッセージを送ります</span></div>${person('ボブ',forward?'受け手':'送り手')}</div><div class="actions">${button('向きを入れ替える','switch-direction','secondary')}${button('この向きで始める','choose-direction')}</div></div></section>`);document.querySelector('#switch-direction').onclick=()=>{state.direction=forward?'bob-alice':'alice-bob';renderPublic()};document.querySelector('#choose-direction').onclick=()=>{state.step=2;renderPublic()}}
  else if(state.step===2){setScreen(`<section class="screen">${head('第2段階｜鍵を選ぶ','暗号化に使う鍵を選ぼう',`${sender}が「テスト範囲は3章」と送ります．`,2,5)}<div class="scene-ribbon"><span class="face">👩‍💻</span><span class="line"></span><span>📨</span><span class="line"></span><span class="face">👨‍💻</span></div><div class="panel"><h2 class="question">${sender}は，どの鍵を使う？</h2>${keyCards(allKeys,state.encryptKey)}<div class="learning-tip"><span>💡</span><p><b>考えるヒント</b><small>鍵の名前だけでなく，「だれが持っているか」も見よう．</small></p></div><div class="actions">${button('通信を始める','send-message','primary',!state.encryptKey)}</div></div></section>`);bindKeys('encryptKey',renderPublic);document.querySelector('#send-message').onclick=()=>{state.step=3;renderPublic()}}
  else if(state.step===3){const view=observeEncryption(state.encryptKey,sender,receiver);setScreen(`<section class="screen">${head('第3段階｜盗み見を確認','通信中のイブを観察しよう','起きたことを見て，通信を続けられるか相談しよう．',3,5)}<div class="panel"><div class="observation"><div class="big-icon">${view.icon}</div><h2>${view.title}</h2><p>${view.text}</p><div class="evidence"><div><strong>送られたもの</strong><span>${view.packet}</span></div><span>→</span><div><strong>イブが使える鍵</strong><span>${view.eveKey}</span></div></div>${view.notice?`<div class="notice">${view.notice}</div>`:''}</div><div class="actions">${button('鍵選びからやり直す','restart-public','secondary')}${view.canContinue?button(`${receiver}が元に戻す`,'to-decrypt'):''}</div></div></section>`);document.querySelector('#restart-public').onclick=()=>{state.step=2;state.encryptKey=null;renderPublic()};if(view.canContinue)document.querySelector('#to-decrypt').onclick=()=>{state.step=4;renderPublic()}}
  else if(state.step===4){setScreen(`<section class="screen">${head('第4段階｜元に戻す','受け手が暗号文を元に戻す',`${receiver}は読めない形のメッセージを受け取りました．`,4,5)}<div class="panel"><div class="scene-ribbon"><span class="face">📨</span><span class="line"></span><span class="face">🔑</span><span class="line"></span><span class="face">📖</span></div><h2 class="question">${receiver}は，どの鍵なら読める？</h2>${keyCards(allKeys,state.decryptKey)}<div class="actions">${button('通信の最初からやり直す','restart-all','secondary')}${button('この鍵で元に戻す','decrypt','primary',!state.decryptKey)}</div></div></section>`);bindKeys('decryptKey',renderPublic);document.querySelector('#restart-all').onclick=()=>{state.step=2;state.encryptKey=null;state.decryptKey=null;renderPublic()};document.querySelector('#decrypt').onclick=()=>{if(canDecrypt(state.encryptKey,state.decryptKey,receiver)){state.step=5;renderPublic()}else renderDecryptObservation(receiver)}}
  else{const enc=forward?'ボブの公開鍵':'アリスの公開鍵',dec=forward?'ボブの秘密鍵':'アリスの秘密鍵';setScreen(`<section class="screen success-screen"><div class="success-mark">🎉</div><p class="kicker">ミッション達成</p><h1>安全な通信に成功！</h1><p class="lead">イブには読まれず，${receiver}だけがメッセージを元に戻せました．</p><div class="flow-summary"><span>🔑 ${enc}</span><b>→ 読めない形にする →</b><span>📨 暗号文</span><b>→ 元に戻す →</b><span>🔑 ${dec}</span></div><div class="actions">${button('反対向きの通信に挑戦','reverse')}${button('ミッション選択へ','home-success','secondary')}</div></section>`);document.querySelector('#reverse').onclick=()=>{state.direction=forward?'bob-alice':'alice-bob';state.step=2;state.encryptKey=null;state.decryptKey=null;renderPublic()};document.querySelector('#home-success').onclick=showHome}
}
function observeEncryption(key,sender,receiver){const rid=receiver==='アリス'?'alice':'bob',sid=sender==='アリス'?'alice':'bob';if(key===`${rid}-private`)return{icon:'🚫🔑',title:'通信を始められない',text:`${receiver}の秘密鍵は，${receiver}だけが持っています．${sender}はこの鍵を使えません．`,packet:'まだ送られていない',eveKey:'なし',notice:'だれがその鍵を持っているかを確かめよう．',canContinue:false};if(key===`${sid}-private`)return{icon:'🕵️👁️',title:'イブが内容を読めた',text:`${sender}の公開鍵はだれでも使えます．イブはその鍵で内容を読みました．`,packet:'読めない形にしたデータ',eveKey:`${sender}の公開鍵`,notice:'ここで通信を止めて，別の鍵でやり直そう．',canContinue:false};if(key.endsWith('public'))return{icon:'🕵️🛡️',title:'イブには内容を読めない',text:'イブは暗号文を盗み見しましたが，対応する秘密鍵を持っていません．',packet:'◆◇■△…（暗号文）',eveKey:'対応する秘密鍵なし',notice:'受け手が読めるかどうかは，まだ分かりません．',canContinue:true};return{icon:'❓',title:'通信の状態を確かめられない',text:'選んだ鍵では先へ進めません．',packet:'なし',eveKey:'なし',canContinue:false}}
function canDecrypt(enc,dec,receiver){return(receiver==='アリス'&&enc==='alice-public'&&dec==='alice-private')||(receiver==='ボブ'&&enc==='bob-public'&&dec==='bob-private')}
function renderDecryptObservation(receiver){const key=allKeys.find(k=>k.id===state.decryptKey);setScreen(`<section class="screen">${head('第4段階｜試した結果','元の文章には戻らなかった','成功画面が出ない理由を，二人で考えよう．',4,5)}<div class="panel"><div class="observation"><div class="big-icon">📨❓</div><h2>メッセージは読めないまま</h2><p>${receiver}が「${key.owner}」を使いましたが，暗号文は元の文章に戻りませんでした．</p><div class="evidence"><div><strong>受け取ったもの</strong><span>◆◇■△…</span></div><span>＋</span><div><strong>試した鍵</strong><span>🔑 ${key.owner}</span></div></div></div><div class="actions">${button('別の鍵を試す','try-another')}${button('通信の最初からやり直す','restart-after-decrypt','secondary')}</div></div></section>`);document.querySelector('#try-another').onclick=()=>{state.decryptKey=null;state.step=4;renderPublic()};document.querySelector('#restart-after-decrypt').onclick=()=>{state.encryptKey=null;state.decryptKey=null;state.step=2;renderPublic()}}

function renderShared(){const keys=[{id:'shared',label:'共通鍵',owner:'アリスとボブの共通鍵',note:'二人が同じ鍵を持つ'},{id:'alice-private',label:'秘密鍵',owner:'アリスの秘密鍵',note:'アリスだけが持つ'},{id:'eve-public',label:'公開鍵',owner:'イブの公開鍵',note:'だれでも使える'}];if(state.step===1){setScreen(`<section class="screen">${head('第1ミッション｜共通鍵暗号','二人で同じ鍵を使う','アリスとボブが同じ鍵を持っているとします．',1,3)}<div class="scene-ribbon"><span class="face">👩‍💻</span><span class="line"></span><span class="face">🔑</span><span class="line"></span><span class="face">👨‍💻</span></div><div class="panel"><h2 class="question">アリスが使う鍵はどれ？</h2>${keyCards(keys,state.encryptKey)}<div class="actions">${button('通信を始める','shared-send','primary',!state.encryptKey)}</div></div></section>`);bindKeys('encryptKey',renderShared);document.querySelector('#shared-send').onclick=()=>{state.step=2;renderShared()}}else if(state.step===2){const safe=state.encryptKey==='shared';setScreen(`<section class="screen">${head('第2段階｜通信を観察','イブとボブを見てみよう','起きたことから，鍵の役割を考えよう．',2,3)}<div class="panel"><div class="observation"><div class="big-icon">${safe?'🕵️🛡️👨‍💻':'🕵️👁️'}</div><h2>${safe?'イブには読めず，ボブは読めた':'二人だけの秘密を守れない'}</h2><p>${safe?'ボブはアリスと共有している同じ鍵で元に戻しました．':'選んだ鍵で起きたことを見て，別の鍵を試そう．'}</p></div><div class="actions">${button('やり直す','shared-retry','secondary')}${safe?button('結果を確認','shared-finish'):''}</div></div></section>`);document.querySelector('#shared-retry').onclick=()=>{state.step=1;state.encryptKey=null;renderShared()};if(safe)document.querySelector('#shared-finish').onclick=()=>{state.step=3;renderShared()}}else{setScreen(`<section class="screen success-screen"><div class="success-mark">🎉</div><p class="kicker">ミッション達成</p><h1>共通鍵で通信できた！</h1><p class="lead">読めない形にするときも元に戻すときも，二人が共有する同じ鍵を使いました．</p><div class="actions">${button('ミッション選択へ','shared-home')}</div></section>`);document.querySelector('#shared-home').onclick=showHome}}

async function sha256(text){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return[...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function renderSignature(){if(state.step===1){setScreen(`<section class="screen">${head('第3ミッション｜デジタル署名','文章から署名を作ろう','署名は，文章を秘密にするためのものではありません．',1,4)}<div class="panel"><div class="purpose-note">🔍 確かめること：送り手はアリスか／送った後に書き換えられていないか</div><div class="signature-input"><label for="sign-message">アリスのメッセージ</label><textarea id="sign-message" rows="3">明日の集合は10時です</textarea><div class="learning-tip"><span>🖐️</span><p><b>ハッシュ値は「文章の指紋」</b><small>文章が少しでも変わると，まったく違う値になります．</small></p></div>${button('文章の指紋を作る','make-hash')}</div></div></section>`);document.querySelector('#make-hash').onclick=async()=>{state.originalMessage=document.querySelector('#sign-message').value;state.signedHash=await sha256(state.originalMessage);state.step=2;renderSignature()}}else if(state.step===2){setScreen(`<section class="screen">${head('第2段階｜署名を作る','アリスが署名する','文章から作った「指紋」を使います．',2,4)}<div class="panel"><div class="evidence"><div><strong>文章の指紋（ハッシュ値）</strong><span class="hash">${state.signedHash}</span></div><span>＋</span><div><strong>署名に使う鍵</strong><span>🔑 アリスの秘密鍵</span></div></div><div class="observation"><div class="big-icon">✍️🔑</div><p>アリスの秘密鍵で署名データを作ります．</p></div><div class="actions">${button('署名してボブへ送る','sign-send')}</div></div></section>`);document.querySelector('#sign-send').onclick=()=>{state.step=3;renderSignature()}}else{setScreen(`<section class="screen">${head('第3段階｜署名を確かめる','ボブが署名を確かめる','確かめる前に，イブが文章を書き換える場合も試せます．',3,4)}<div class="panel"><div class="signature-input"><label for="received-message">ボブが受け取ったメッセージ</label><textarea id="received-message" rows="3">${state.originalMessage}</textarea><div class="actions">${button('イブが10時を11時に書き換える','tamper','secondary')}${button('アリスの公開鍵で確かめる','verify')}</div></div></div></section>`);document.querySelector('#tamper').onclick=()=>{document.querySelector('#received-message').value=document.querySelector('#received-message').value.replace('10時','11時')};document.querySelector('#verify').onclick=async()=>{const received=await sha256(document.querySelector('#received-message').value);renderSignatureResult(received===state.signedHash,received)}}}
function renderSignatureResult(ok,received){setScreen(`<section class="screen ${ok?'success-screen':''}">${ok?'<div class="success-mark">🎉</div>':'<div class="big-icon">🖐️≠🖐️</div>'}${head('第4段階｜確かめた結果',ok?'署名を確かめられた！':'二つの「文章の指紋」がちがう',ok?'アリスが署名した後，文章は変わっていません．':'受け取った文章は，署名したときの内容と異なります．',4,4)}<div class="panel"><div class="evidence"><div><strong>署名したときの指紋</strong><span class="hash">${state.signedHash}</span></div><span>${ok?'＝':'≠'}</span><div><strong>受け取ったときの指紋</strong><span class="hash">${received}</span></div></div><div class="actions">${button('最初から試す','signature-retry','secondary')}${ok?button('ミッション選択へ','signature-home'):button('メッセージに戻る','signature-back')}</div></div></section>`);document.querySelector('#signature-retry').onclick=()=>{state.step=1;renderSignature()};if(ok)document.querySelector('#signature-home').onclick=showHome;else document.querySelector('#signature-back').onclick=()=>{state.step=3;renderSignature()}}
showHome();
